### ISSUE TITLE
Public Suffix List (PSL) Updates Too Often 

### ISSUE THREAD

**Issue by Matthew-Grayson** [dhs-ncats/trustymail#132]
# 🐛 Summary #

When using the argument '--psl-file=public_suffix.dat', trustymail often updates the PSL when the local version is already up-to-date.

Right now, Trustymail's code logic checks the last modified field of the local PSL using stat.st_mtime, and if the last modified time is more than 24 hours ago, Trustymail downloads a new PSL.

The problem is, the last modified time for a newly downloaded PSL might be 3 days ago. When this is the case, Trustymail downloads a new PSL each time it is run, even though the newest PSL is stored locally.

## To reproduce ##

1. Run `trustymail --psl-file=public_suffix_list.dat cisa.gov`
2. Check to see if the public_suffix_list.dat is more than 24 hours old
3. Repeat step one and verify that an output statement warns, a script is being run to download a new PSL.

## Expected behavior ##

PSL should only be downloaded when the local version is older than that found at publicsuffix.org.

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by chrislandis** [comment]
I am glad to see this issue is close to being resolved via the pull request cited above.  Thank you!

In the meantime, a simple work-around when needing to scan more than one domain per day is to open `public_suffix_list.dat` in a text editor, add a space to a preexisting comment, and save the file so as to update its modified date.  On the next day (specifically, >24 hours from your manual modification of the locally stored PSL file), when you run `trustymail` it will once again try to download an updated version.  As such, you would need to implement this workaround each day after your first `trustymail` scan.

As an FYI, the warning about not trying to download the PSL more than once per day comes from [Python's `publicsuffixlist` package](https://github.com/ko-zu/psl/blob/master/publicsuffixlist/update.py).
