### ISSUE TITLE
trustymail should be case-insensitive w/r/t DNS

### ISSUE THREAD

**Issue by h-m-f-t** [dhs-ncats/trustymail#39]
[RFC 4343](https://tools.ietf.org/html/rfc4343) indicates that DNS names are case-insensitive. We already .lower() domains from input, but we should also allow for any case when we check for the validity of [SPF](https://github.com/dhs-ncats/trustymail/blob/d4bb68aefa03fc61aa4a454295ebccf0154f6748/trustymail/trustymail.py#L249-L253) and [DMARC](https://github.com/dhs-ncats/trustymail/blob/d4bb68aefa03fc61aa4a454295ebccf0154f6748/trustymail/trustymail.py#L315) records.

This currently affects guideline.gov, which trustymail says has no SPF record.

```bash
$ host -t txt guideline.gov
<snip>
guideline.gov descriptive text "v=SPF1 mx include:spf.intermedia.net -all"
```

**Comment by jsf9k** [comment]
@h-m-f-t, I see that `trustymail` is finding that `guideline.gov` has no SPF record because their record starts with `v=SPF1` instead of the `v=spf1` it is expecting.  I also see [here](https://tools.ietf.org/html/rfc7208#section-4.6.1) that the mechanism and modifier names are case-insensitive.  On the other hand, it says [here](https://tools.ietf.org/html/rfc7208#section-4.5) that an SPF record *must* start with a version section of *exactly* "v=spf1".  I interpret this as meaning that the tests [here](https://github.com/dhs-ncats/trustymail/blob/develop/trustymail/trustymail.py#L246) and [here](https://github.com/dhs-ncats/trustymail/blob/develop/trustymail/trustymail.py#L360) should be case-sensitive.  I'm not certain that is correct, though.

I do agree that if we inspect the SPF record contents (looking for "MX" or "mx", for example) then that would be case-insensitive.  For us, though, that inspection is handled by the `pyspf` library.  

I have more research to do to figure out exactly how case impacts `trustymail`'s DMARC-related code.

I believe [RFC 4343](https://tools.ietf.org/html/rfc4343), which you referenced, only speaks to the case-insensitivity of DNS *names*.

**Comment by h-m-f-t** [comment]
>On the other hand, it says [here](https://tools.ietf.org/html/rfc7208#section-4.5) that an SPF record must start with a version section of exactly v=spf1

That ^ looks like really good evidence that I'm incorrect and we _should_ flag `v=SPF1` as invalid. Thanks for drilling into this, @jsf9k.
