### ISSUE TITLE
How can I notify .gov domain owners of problems with their SPF/DMARC records?

### ISSUE THREAD

**Issue by seanthegeek** [dhs-ncats/trustymail#43]
I spent the last month or so writing my own parsers for SPF and DMARC, and I just learned this project exists! D'oh! My code is not as clean as yours, but it is more strict about how it validates SPF and DMARC records. I'll contribute some code for issue #33 soon 😄 

https://domainaware.github.io/checkdmarc/

Anyway, I tested my script against a list of high-profile (risk of fraud or political activism) departments/agencies, I ran those separately, and I found that a few of the domains have errors in their SPF and/or DMARC records (if they have them at all):

- cbo.gov
  - MX record error: mxb-001ec201.gslb.pphosted.com does not have any A or AAAA records
   - Parsing the SPF record requires more than the 10 maximum DNS queries https://tools.ietf.org/html/rfc7208#section-4.6.4
- cia.gov:
  - Unnecessary SPF mechanisms mx:cia.gov mx:ucia.gov
- dhs.gov
  - hq.dhs.gov does not indicate that it accepts DMARC reports about dhs.gov - https://tools.ietf.org/html/rfc7489#section-7.1
- epa.gov
  - MX record error: grid1f6.gseg.att.com does not have any A or AAAA records;grid126.gseg.att.com does not have any A or AAAA records
- gsa.gov
  - Parsing the SPF record requires more than the 10 maximum DNS queries https://tools.ietf.org/html/rfc7208#section-4.6.4
- fema.gov
  - fema.dhs.gov does not indicate that it accepts DMARC reports about fema.gov - https://tools.ietf.org/html/rfc7489#section-7.1
- hhs.gov
  - SPF warning: The ptr mechanism should not be used - https://tools.ietf.org/html/rfc7208#section-5.5
- interior.gov
  - interior-gov.mail.protection.outlook.com does not have any A or AAAA records
    - The Department of the Interior uses doi,gov for email, which has Google MX records. They should change interior.gov to match (so email aliases work), or remove this MX record
- irs.gov
  - SPF include qai.irs.gov does not resolve (SERVFAIL)
  - ofdp.irs.gov does not indicate that it accepts DMARC reports about irs.gov - https://tools.ietf.org/html/rfc7489#section-7.1
- opm.gov
  - Parsing the SPF record requires more than the 10 maximum DNS queries https://tools.ietf.org
    -Note: Their SPF record is literally monstrous - not good for OPSEC or the SPF standard 
/html/rfc7208#section-4.6.4
- nasa.gov
  - mail.nasa.gov does not indicate that it accepts DMARC reports about nasa.gov - https://tools.ietf.org/html/rfc7489#section-7.1
- ofdp.irs.gov
  - DMARC error: Tag fo must have one of the following values: 0,1,d,s - not 0:1:d:s
- sec.gov
  - SOCReporting@sec.gov is not a valid DMARC report URI
- uscg.mil
  - Has a SPF record where a DMARC record should be

**Comment by h-m-f-t** [comment]
@seanthegeek 👋 hi there! Nice work on your tool, and excellent documentation! We would welcome your contributions, especially regarding #33.

Similar to the process described in [this blog post](https://18f.gsa.gov/2017/01/06/open-source-collaboration-across-agencies-to-improve-https-deployment/), where we deliver HTTPS results to agencies, we also deliver a Trustworthy Email Report regularly to (federal civilian executive branch [so no CIA]) agencies that contains this very information-- minus #33 info, which is a real need. To wit: just this AM I reached out manually to the DHS team notifying them that they won't receive reports from non-`hq.dhs.gov` domains!

I'm going to close this issue, since it's already happening (by and large). Hope to see you in some pull requests. 👍
